// app/layout.tsx
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: {
        default: "nextjs foor",
        template: "%s | nextjs foor",
    },
    description: "Generated by Next.js",
};

export default function AuthtLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <main className="bg-violet-950 w-full flex-grow flex justify-center items-center">
            {children}
        </main>
    );
}
