// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import "./fonts.css"

export const metadata: Metadata = {
  title: {
    default: "nextjs foor",
    template: "%s | nextjs foor",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        {children}
      </body>
    </html>
  );
}
